### ISSUE TITLE
Update ebean-agent version to 11.1.3

### ISSUE THREAD

**Issue by ajcamilo** [ebean-orm-tools/ebean-eclipse-enhancer#9]
Update ebean-agent version to 11.1.3

**Comment by rbygrave** [comment]
Yes, I see this (Eclise plugin is behind).  Just releasing 11.3.1 of the agent now.

Note that there is another planned change to come shortly to simplify some of the enhancement (transactional and removing property change support).

**Comment by rbygrave** [comment]
Done. It was updated to 11.5.1  ... you can download it etc.  Closing.
